-- Seed data for 214 Kangxi Radicals
-- Data sourced from Kanji Alive (CC BY 4.0)

INSERT INTO radicals (radical_number, radical_character, radical_name_en, radical_name_jp, stroke_count, meaning, position) VALUES
-- 1 stroke
(1, '一', 'one', 'いち', 1, 'one, horizontal stroke', NULL),
(2, '丨', 'line', 'ぼう', 1, 'vertical line, stick', NULL),
(3, '丶', 'dot', 'てん', 1, 'dot, tick', NULL),
(4, '丿', 'slash', 'の', 1, 'bend, slash', NULL),
(5, '乙', 'second', 'おつ', 1, 'second, the latter', NULL),
(6, '亅', 'hook', 'はねぼう', 1, 'hook, barb', NULL),

-- 2 strokes
(7, '二', 'two', 'に', 2, 'two', NULL),
(8, '亠', 'lid', 'なべぶた', 2, 'pot lid, top', 'kanmuri'),
(9, '人', 'person', 'ひと', 2, 'person, human', NULL),
(10, '儿', 'legs', 'にんにょう', 2, 'human legs', 'ashi'),
(11, '入', 'enter', 'いる', 2, 'enter, put in', NULL),
(12, '八', 'eight', 'はち', 2, 'eight, divide', NULL),
(13, '冂', 'upside-down box', 'けいがまえ', 2, 'inverted box', 'kamae'),
(14, '冖', 'cover', 'わかんむり', 2, 'cover, crown', 'kanmuri'),
(15, '冫', 'ice', 'にすい', 2, 'ice, cold', 'hen'),
(16, '几', 'table', 'つくえ', 2, 'table, bench', NULL),
(17, '凵', 'container', 'うけばこ', 2, 'open box, container', 'kamae'),
(18, '刀', 'sword', 'かたな', 2, 'sword, knife', NULL),
(19, '力', 'power', 'ちから', 2, 'power, strength', NULL),
(20, '勹', 'wrap', 'つつみがまえ', 2, 'wrap, embrace', 'kamae'),
(21, '匕', 'spoon', 'さじ', 2, 'spoon, ladle', NULL),
(22, '匚', 'box', 'はこがまえ', 2, 'box, hiding', 'kamae'),
(23, '匸', 'hiding', 'かくしがまえ', 2, 'conceal', 'kamae'),
(24, '十', 'ten', 'じゅう', 2, 'ten, cross', NULL),
(25, '卜', 'divination', 'ぼく', 2, 'divination, fortune-telling', NULL),
(26, '卩', 'seal', 'ふしづくり', 2, 'seal, kneeling person', 'tsukuri'),
(27, '厂', 'cliff', 'がんだれ', 2, 'cliff, factory', 'tare'),
(28, '厶', 'private', 'む', 2, 'private, secret', NULL),
(29, '又', 'again', 'また', 2, 'again, right hand', NULL),

-- 3 strokes
(30, '口', 'mouth', 'くち', 3, 'mouth, opening', NULL),
(31, '囗', 'enclosure', 'くにがまえ', 3, 'enclosure, border', 'kamae'),
(32, '土', 'earth', 'つち', 3, 'earth, ground, soil', NULL),
(33, '士', 'scholar', 'さむらい', 3, 'scholar, samurai', NULL),
(34, '夂', 'go', 'ふゆがしら', 3, 'go slowly, winter', 'kanmuri'),
(35, '夊', 'go slowly', 'すいにょう', 3, 'go slowly', 'ashi'),
(36, '夕', 'evening', 'ゆうべ', 3, 'evening, moon', NULL),
(37, '大', 'big', 'だい', 3, 'big, large, great', NULL),
(38, '女', 'woman', 'おんな', 3, 'woman, female', NULL),
(39, '子', 'child', 'こ', 3, 'child, seed', NULL),
(40, '宀', 'roof', 'うかんむり', 3, 'roof, house', 'kanmuri'),
(41, '寸', 'inch', 'すん', 3, 'inch, small', NULL),
(42, '小', 'small', 'しょう', 3, 'small, little', NULL),
(43, '尢', 'lame', 'まげあし', 3, 'lame, crooked', NULL),
(44, '尸', 'corpse', 'しかばね', 3, 'corpse, body', 'tare'),
(45, '屮', 'sprout', 'てつ', 3, 'sprout, grass', NULL),
(46, '山', 'mountain', 'やま', 3, 'mountain', NULL),
(47, '巛', 'river', 'かわ', 3, 'river, stream', NULL),
(48, '工', 'work', 'たくみ', 3, 'work, craft', NULL),
(49, '己', 'oneself', 'おのれ', 3, 'oneself, self', NULL),
(50, '巾', 'cloth', 'はば', 3, 'cloth, towel, turban', NULL),
(51, '干', 'dry', 'ほす', 3, 'dry, shield', NULL),
(52, '幺', 'short thread', 'いとがしら', 3, 'short thread, tiny', NULL),
(53, '广', 'dotted cliff', 'まだれ', 3, 'dotted cliff, lean-to', 'tare'),
(54, '廴', 'long stride', 'えんにょう', 3, 'long stride', 'nyou'),
(55, '廾', 'two hands', 'にじゅうあし', 3, 'two hands, twenty', 'ashi'),
(56, '弋', 'ceremony', 'しきがまえ', 3, 'ceremony, stake', NULL),
(57, '弓', 'bow', 'ゆみ', 3, 'bow (weapon)', NULL),
(58, '彐', 'pig snout', 'けいがしら', 3, 'pig snout, pig head', NULL),
(59, '彡', 'hair', 'さんづくり', 3, 'hair, decoration, bristle', 'tsukuri'),
(60, '彳', 'step', 'ぎょうにんべん', 3, 'step, walk slowly', 'hen'),

-- 4 strokes
(61, '心', 'heart', 'こころ', 4, 'heart, mind, spirit', NULL),
(62, '戈', 'spear', 'ほこ', 4, 'spear, halberd', NULL),
(63, '戶', 'door', 'と', 4, 'door, house', NULL),
(64, '手', 'hand', 'て', 4, 'hand', NULL),
(65, '支', 'branch', 'しにょう', 4, 'branch, support', NULL),
(66, '攴', 'rap', 'ぼくづくり', 4, 'rap, strike', 'tsukuri'),
(67, '文', 'writing', 'ぶん', 4, 'writing, literature', NULL),
(68, '斗', 'dipper', 'と', 4, 'dipper, measuring cup', NULL),
(69, '斤', 'axe', 'きん', 4, 'axe, catty', NULL),
(70, '方', 'direction', 'ほう', 4, 'direction, square', NULL),
(71, '无', 'not', 'なし', 4, 'not, without', NULL),
(72, '日', 'sun', 'ひ', 4, 'sun, day, time', NULL),
(73, '曰', 'say', 'いわく', 4, 'say, speak', NULL),
(74, '月', 'moon', 'つき', 4, 'moon, month, flesh', NULL),
(75, '木', 'tree', 'き', 4, 'tree, wood', NULL),
(76, '欠', 'lack', 'あくび', 4, 'lack, yawn, breathe', NULL),
(77, '止', 'stop', 'とめる', 4, 'stop, halt', NULL),
(78, '歹', 'death', 'がつ', 4, 'death, bones, decay', NULL),
(79, '殳', 'weapon', 'るまた', 4, 'weapon, lance shaft', 'tsukuri'),
(80, '毋', 'do not', 'はは', 4, 'do not, mother', NULL),
(81, '比', 'compare', 'くらべる', 4, 'compare, compete', NULL),
(82, '毛', 'fur', 'け', 4, 'fur, hair, feather', NULL),
(83, '氏', 'clan', 'うじ', 4, 'clan, family name', NULL),
(84, '气', 'steam', 'きがまえ', 4, 'steam, vapor, spirit', 'kamae'),
(85, '水', 'water', 'みず', 4, 'water, liquid', NULL),
(86, '火', 'fire', 'ひ', 4, 'fire, flame', NULL),
(87, '爪', 'claw', 'つめ', 4, 'claw, nail', NULL),
(88, '父', 'father', 'ちち', 4, 'father', NULL),
(89, '爻', 'mix', 'こう', 4, 'mix, mingle', NULL),
(90, '爿', 'split wood', 'しょうへん', 4, 'split wood, bed', 'hen'),
(91, '片', 'slice', 'かた', 4, 'slice, piece', NULL),
(92, '牙', 'fang', 'きば', 4, 'fang, tusk', NULL),
(93, '牛', 'cow', 'うし', 4, 'cow, ox, cattle', NULL),
(94, '犬', 'dog', 'いぬ', 4, 'dog', NULL),

-- 5 strokes
(95, '玄', 'profound', 'げん', 5, 'profound, mysterious', NULL),
(96, '玉', 'jade', 'たま', 5, 'jade, jewel, ball', NULL),
(97, '瓜', 'melon', 'うり', 5, 'melon', NULL),
(98, '瓦', 'tile', 'かわら', 5, 'tile, roof tile', NULL),
(99, '甘', 'sweet', 'あまい', 5, 'sweet, pleasant', NULL),
(100, '生', 'life', 'いきる', 5, 'life, birth, raw', NULL),
(101, '用', 'use', 'もちいる', 5, 'use, employ', NULL),
(102, '田', 'rice field', 'た', 5, 'rice field, paddy', NULL),
(103, '疋', 'bolt of cloth', 'ひき', 5, 'bolt of cloth, counter', NULL),
(104, '疒', 'sickness', 'やまいだれ', 5, 'sickness, illness', 'tare'),
(105, '癶', 'footsteps', 'はつがしら', 5, 'footsteps, departing', 'kanmuri'),
(106, '白', 'white', 'しろ', 5, 'white, clear', NULL),
(107, '皮', 'skin', 'かわ', 5, 'skin, hide, leather', NULL),
(108, '皿', 'dish', 'さら', 5, 'dish, plate', NULL),
(109, '目', 'eye', 'め', 5, 'eye', NULL),
(110, '矛', 'spear', 'ほこ', 5, 'spear, pike, lance', NULL),
(111, '矢', 'arrow', 'や', 5, 'arrow', NULL),
(112, '石', 'stone', 'いし', 5, 'stone, rock', NULL),
(113, '示', 'show', 'しめす', 5, 'show, reveal, altar', NULL),
(114, '禸', 'track', 'ぐうのあし', 5, 'track, footprint', NULL),
(115, '禾', 'grain', 'のぎ', 5, 'grain, cereal', NULL),
(116, '穴', 'cave', 'あな', 5, 'cave, hole', 'kanmuri'),
(117, '立', 'stand', 'たつ', 5, 'stand, erect', NULL),

-- 6 strokes
(118, '竹', 'bamboo', 'たけ', 6, 'bamboo', 'kanmuri'),
(119, '米', 'rice', 'こめ', 6, 'rice, grain', NULL),
(120, '糸', 'thread', 'いと', 6, 'thread, silk', NULL),
(121, '缶', 'jar', 'かん', 6, 'jar, pot, tin can', NULL),
(122, '网', 'net', 'あみがしら', 6, 'net, network', 'kanmuri'),
(123, '羊', 'sheep', 'ひつじ', 6, 'sheep, goat', NULL),
(124, '羽', 'feather', 'はね', 6, 'feather, wing', NULL),
(125, '老', 'old', 'おいる', 6, 'old, aged', NULL),
(126, '而', 'and', 'しかして', 6, 'and, yet, beard', NULL),
(127, '耒', 'plow', 'すき', 6, 'plow, farming', 'hen'),
(128, '耳', 'ear', 'みみ', 6, 'ear', NULL),
(129, '聿', 'brush', 'ふで', 6, 'brush, writing implement', NULL),
(130, '肉', 'meat', 'にく', 6, 'meat, flesh', NULL),
(131, '臣', 'minister', 'しん', 6, 'minister, official', NULL),
(132, '自', 'self', 'みずから', 6, 'self, oneself', NULL),
(133, '至', 'arrive', 'いたる', 6, 'arrive, reach', NULL),
(134, '臼', 'mortar', 'うす', 6, 'mortar, mill', NULL),
(135, '舌', 'tongue', 'した', 6, 'tongue', NULL),
(136, '舛', 'oppose', 'まいあし', 6, 'oppose, dance', NULL),
(137, '舟', 'boat', 'ふね', 6, 'boat, ship', NULL),
(138, '艮', 'stopping', 'こん', 6, 'stopping, boundary', NULL),
(139, '色', 'color', 'いろ', 6, 'color', NULL),
(140, '艸', 'grass', 'くさかんむり', 6, 'grass, plant', 'kanmuri'),
(141, '虍', 'tiger', 'とらがしら', 6, 'tiger stripes', 'kanmuri'),
(142, '虫', 'insect', 'むし', 6, 'insect, bug, worm', NULL),
(143, '血', 'blood', 'ち', 6, 'blood', NULL),
(144, '行', 'go', 'ぎょうがまえ', 6, 'go, act, walk', 'kamae'),
(145, '衣', 'clothes', 'ころも', 6, 'clothes, garment', NULL),
(146, '襾', 'west', 'にし', 6, 'west, cover', 'kanmuri'),

-- 7 strokes
(147, '見', 'see', 'みる', 7, 'see, view', NULL),
(148, '角', 'horn', 'つの', 7, 'horn, angle', NULL),
(149, '言', 'say', 'いう', 7, 'say, speak, word', NULL),
(150, '谷', 'valley', 'たに', 7, 'valley', NULL),
(151, '豆', 'bean', 'まめ', 7, 'bean, pea', NULL),
(152, '豕', 'pig', 'いのこ', 7, 'pig, boar', NULL),
(153, '豸', 'badger', 'むじな', 7, 'badger, cat family', NULL),
(154, '貝', 'shell', 'かい', 7, 'shell, money', NULL),
(155, '赤', 'red', 'あか', 7, 'red', NULL),
(156, '走', 'run', 'はしる', 7, 'run', NULL),
(157, '足', 'foot', 'あし', 7, 'foot, leg', NULL),
(158, '身', 'body', 'み', 7, 'body, oneself', NULL),
(159, '車', 'car', 'くるま', 7, 'car, vehicle, wheel', NULL),
(160, '辛', 'bitter', 'からい', 7, 'bitter, spicy', NULL),
(161, '辰', 'dragon', 'たつ', 7, 'dragon, time', NULL),
(162, '辵', 'walk', 'しんにょう', 7, 'walk, movement', 'nyou'),
(163, '邑', 'city', 'おおざと', 7, 'city, village', 'tsukuri'),
(164, '酉', 'sake', 'とり', 7, 'sake, wine, west bird', NULL),
(165, '釆', 'separate', 'のごめ', 7, 'separate, distinguish', NULL),
(166, '里', 'village', 'さと', 7, 'village, mile', NULL),

-- 8 strokes
(167, '金', 'gold', 'かね', 8, 'gold, metal, money', NULL),
(168, '長', 'long', 'ながい', 8, 'long, leader', NULL),
(169, '門', 'gate', 'もん', 8, 'gate, door', 'kamae'),
(170, '阜', 'mound', 'こざとへん', 8, 'mound, hill', 'hen'),
(171, '隶', 'slave', 'れいづくり', 8, 'slave, servant', NULL),
(172, '隹', 'short-tailed bird', 'ふるとり', 8, 'short-tailed bird', NULL),
(173, '雨', 'rain', 'あめ', 8, 'rain', 'kanmuri'),
(174, '青', 'blue', 'あお', 8, 'blue, green', NULL),
(175, '非', 'wrong', 'あらず', 8, 'wrong, not', NULL),

-- 9 strokes
(176, '面', 'face', 'めん', 9, 'face, mask, surface', NULL),
(177, '革', 'leather', 'かわ', 9, 'leather, hide', NULL),
(178, '韋', 'tanned leather', 'なめしがわ', 9, 'tanned leather', NULL),
(179, '韭', 'leek', 'にら', 9, 'leek, scallion', NULL),
(180, '音', 'sound', 'おと', 9, 'sound, noise', NULL),
(181, '頁', 'page', 'おおがい', 9, 'page, head', 'tsukuri'),
(182, '風', 'wind', 'かぜ', 9, 'wind', NULL),
(183, '飛', 'fly', 'とぶ', 9, 'fly', NULL),
(184, '食', 'eat', 'しょく', 9, 'eat, food', NULL),
(185, '首', 'neck', 'くび', 9, 'neck, head', NULL),
(186, '香', 'fragrant', 'か', 9, 'fragrant, incense', NULL),

-- 10 strokes
(187, '馬', 'horse', 'うま', 10, 'horse', NULL),
(188, '骨', 'bone', 'ほね', 10, 'bone', NULL),
(189, '高', 'tall', 'たかい', 10, 'tall, high', NULL),
(190, '髟', 'hair', 'かみがしら', 10, 'long hair', 'kanmuri'),
(191, '鬥', 'fight', 'とうがまえ', 10, 'fight, quarrel', 'kamae'),
(192, '鬯', 'sacrificial wine', 'ちょう', 10, 'sacrificial wine', NULL),
(193, '鬲', 'tripod', 'れき', 10, 'tripod, cauldron', NULL),
(194, '鬼', 'demon', 'おに', 10, 'demon, ghost', NULL),

-- 11 strokes
(195, '魚', 'fish', 'うお', 11, 'fish', NULL),
(196, '鳥', 'bird', 'とり', 11, 'bird', NULL),
(197, '鹵', 'salt', 'ろ', 11, 'salt, bitter', NULL),
(198, '鹿', 'deer', 'しか', 11, 'deer', NULL),
(199, '麥', 'wheat', 'むぎ', 11, 'wheat, barley', NULL),
(200, '麻', 'hemp', 'あさ', 11, 'hemp, flax', NULL),

-- 12 strokes
(201, '黃', 'yellow', 'き', 12, 'yellow', NULL),
(202, '黍', 'millet', 'きび', 12, 'millet', NULL),
(203, '黑', 'black', 'くろ', 12, 'black', NULL),
(204, '黹', 'embroidery', 'ぬいとり', 12, 'embroidery', NULL),

-- 13 strokes
(205, '黽', 'frog', 'べんあし', 13, 'frog, toad', NULL),
(206, '鼎', 'tripod', 'かなえ', 13, 'tripod, cauldron', NULL),
(207, '鼓', 'drum', 'つづみ', 13, 'drum', NULL),
(208, '鼠', 'rat', 'ねずみ', 13, 'rat, mouse', NULL),

-- 14 strokes
(209, '鼻', 'nose', 'はな', 14, 'nose', NULL),
(210, '齊', 'even', 'せい', 14, 'even, equal', NULL),

-- 15 strokes
(211, '齒', 'tooth', 'は', 15, 'tooth', NULL),

-- 16 strokes
(212, '龍', 'dragon', 'りゅう', 16, 'dragon', NULL),
(213, '龜', 'turtle', 'かめ', 16, 'turtle', NULL),

-- 17 strokes
(214, '龠', 'flute', 'やく', 17, 'flute', NULL)

ON CONFLICT (radical_number) DO UPDATE SET
  radical_character = EXCLUDED.radical_character,
  radical_name_en = EXCLUDED.radical_name_en,
  radical_name_jp = EXCLUDED.radical_name_jp,
  stroke_count = EXCLUDED.stroke_count,
  meaning = EXCLUDED.meaning,
  position = EXCLUDED.position;
