-- Seed adjectives table with i-adjectives and their conjugations
-- This inserts all 48 adjectives with pre-computed conjugations

-- N5 Adjectives
INSERT INTO adjectives (dictionary_form, reading, romaji, meaning, adjective_type, jlpt_level, frequency, conjugations) VALUES

-- いい (irregular)
('いい', 'いい', 'ii', 'good', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "いい", "reading": "いい", "romaji": "ii"}, "present_negative": {"kanji": "よくない", "reading": "よくない", "romaji": "yokunai"}, "past_positive": {"kanji": "よかった", "reading": "よかった", "romaji": "yokatta"}, "past_negative": {"kanji": "よくなかった", "reading": "よくなかった", "romaji": "yokunakatta"}, "te_form": {"kanji": "よくて", "reading": "よくて", "romaji": "yokute"}, "adverb": {"kanji": "よく", "reading": "よく", "romaji": "yoku"}}'),

-- Basic descriptive
('悪い', 'わるい', 'warui', 'bad', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "悪い", "reading": "わるい", "romaji": "warui"}, "present_negative": {"kanji": "悪くない", "reading": "わるくない", "romaji": "warukunai"}, "past_positive": {"kanji": "悪かった", "reading": "わるかった", "romaji": "warukatta"}, "past_negative": {"kanji": "悪くなかった", "reading": "わるくなかった", "romaji": "warukunakatta"}, "te_form": {"kanji": "悪くて", "reading": "わるくて", "romaji": "warukute"}, "adverb": {"kanji": "悪く", "reading": "わるく", "romaji": "waruku"}}'),

('大きい', 'おおきい', 'ookii', 'big, large', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "大きい", "reading": "おおきい", "romaji": "ookii"}, "present_negative": {"kanji": "大きくない", "reading": "おおきくない", "romaji": "ookikunai"}, "past_positive": {"kanji": "大きかった", "reading": "おおきかった", "romaji": "ookikatta"}, "past_negative": {"kanji": "大きくなかった", "reading": "おおきくなかった", "romaji": "ookikunakatta"}, "te_form": {"kanji": "大きくて", "reading": "おおきくて", "romaji": "ookikute"}, "adverb": {"kanji": "大きく", "reading": "おおきく", "romaji": "ookiku"}}'),

('小さい', 'ちいさい', 'chiisai', 'small, little', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "小さい", "reading": "ちいさい", "romaji": "chiisai"}, "present_negative": {"kanji": "小さくない", "reading": "ちいさくない", "romaji": "chiisakunai"}, "past_positive": {"kanji": "小さかった", "reading": "ちいさかった", "romaji": "chiisakatta"}, "past_negative": {"kanji": "小さくなかった", "reading": "ちいさくなかった", "romaji": "chiisakunakatta"}, "te_form": {"kanji": "小さくて", "reading": "ちいさくて", "romaji": "chiisakute"}, "adverb": {"kanji": "小さく", "reading": "ちいさく", "romaji": "chiisaku"}}'),

('高い', 'たかい', 'takai', 'expensive, high, tall', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "高い", "reading": "たかい", "romaji": "takai"}, "present_negative": {"kanji": "高くない", "reading": "たかくない", "romaji": "takakunai"}, "past_positive": {"kanji": "高かった", "reading": "たかかった", "romaji": "takakatta"}, "past_negative": {"kanji": "高くなかった", "reading": "たかくなかった", "romaji": "takakunakatta"}, "te_form": {"kanji": "高くて", "reading": "たかくて", "romaji": "takakute"}, "adverb": {"kanji": "高く", "reading": "たかく", "romaji": "takaku"}}'),

('安い', 'やすい', 'yasui', 'cheap, inexpensive', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "安い", "reading": "やすい", "romaji": "yasui"}, "present_negative": {"kanji": "安くない", "reading": "やすくない", "romaji": "yasukunai"}, "past_positive": {"kanji": "安かった", "reading": "やすかった", "romaji": "yasukatta"}, "past_negative": {"kanji": "安くなかった", "reading": "やすくなかった", "romaji": "yasukunakatta"}, "te_form": {"kanji": "安くて", "reading": "やすくて", "romaji": "yasukute"}, "adverb": {"kanji": "安く", "reading": "やすく", "romaji": "yasuku"}}'),

('低い', 'ひくい', 'hikui', 'low, short (height)', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "低い", "reading": "ひくい", "romaji": "hikui"}, "present_negative": {"kanji": "低くない", "reading": "ひくくない", "romaji": "hikukunai"}, "past_positive": {"kanji": "低かった", "reading": "ひくかった", "romaji": "hikukatta"}, "past_negative": {"kanji": "低くなかった", "reading": "ひくくなかった", "romaji": "hikukunakatta"}, "te_form": {"kanji": "低くて", "reading": "ひくくて", "romaji": "hikukute"}, "adverb": {"kanji": "低く", "reading": "ひくく", "romaji": "hikuku"}}'),

-- Temperature
('暑い', 'あつい', 'atsui', 'hot (weather)', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "暑い", "reading": "あつい", "romaji": "atsui"}, "present_negative": {"kanji": "暑くない", "reading": "あつくない", "romaji": "atsukunai"}, "past_positive": {"kanji": "暑かった", "reading": "あつかった", "romaji": "atsukatta"}, "past_negative": {"kanji": "暑くなかった", "reading": "あつくなかった", "romaji": "atsukunakatta"}, "te_form": {"kanji": "暑くて", "reading": "あつくて", "romaji": "atsukute"}, "adverb": {"kanji": "暑く", "reading": "あつく", "romaji": "atsuku"}}'),

('寒い', 'さむい', 'samui', 'cold (weather)', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "寒い", "reading": "さむい", "romaji": "samui"}, "present_negative": {"kanji": "寒くない", "reading": "さむくない", "romaji": "samukunai"}, "past_positive": {"kanji": "寒かった", "reading": "さむかった", "romaji": "samukatta"}, "past_negative": {"kanji": "寒くなかった", "reading": "さむくなかった", "romaji": "samukunakatta"}, "te_form": {"kanji": "寒くて", "reading": "さむくて", "romaji": "samukute"}, "adverb": {"kanji": "寒く", "reading": "さむく", "romaji": "samuku"}}'),

('暖かい', 'あたたかい', 'atatakai', 'warm', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "暖かい", "reading": "あたたかい", "romaji": "atatakai"}, "present_negative": {"kanji": "暖かくない", "reading": "あたたかくない", "romaji": "atatakakunai"}, "past_positive": {"kanji": "暖かかった", "reading": "あたたかかった", "romaji": "atatakakatta"}, "past_negative": {"kanji": "暖かくなかった", "reading": "あたたかくなかった", "romaji": "atatakakunakatta"}, "te_form": {"kanji": "暖かくて", "reading": "あたたかくて", "romaji": "atatakakute"}, "adverb": {"kanji": "暖かく", "reading": "あたたかく", "romaji": "atatakaku"}}'),

('涼しい', 'すずしい', 'suzushii', 'cool', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "涼しい", "reading": "すずしい", "romaji": "suzushii"}, "present_negative": {"kanji": "涼しくない", "reading": "すずしくない", "romaji": "suzushikunai"}, "past_positive": {"kanji": "涼しかった", "reading": "すずしかった", "romaji": "suzushikatta"}, "past_negative": {"kanji": "涼しくなかった", "reading": "すずしくなかった", "romaji": "suzushikunakatta"}, "te_form": {"kanji": "涼しくて", "reading": "すずしくて", "romaji": "suzushikute"}, "adverb": {"kanji": "涼しく", "reading": "すずしく", "romaji": "suzushiku"}}'),

-- New & old
('新しい', 'あたらしい', 'atarashii', 'new', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "新しい", "reading": "あたらしい", "romaji": "atarashii"}, "present_negative": {"kanji": "新しくない", "reading": "あたらしくない", "romaji": "atarashikunai"}, "past_positive": {"kanji": "新しかった", "reading": "あたらしかった", "romaji": "atarashikatta"}, "past_negative": {"kanji": "新しくなかった", "reading": "あたらしくなかった", "romaji": "atarashikunakatta"}, "te_form": {"kanji": "新しくて", "reading": "あたらしくて", "romaji": "atarashikute"}, "adverb": {"kanji": "新しく", "reading": "あたらしく", "romaji": "atarashiku"}}'),

('古い', 'ふるい', 'furui', 'old', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "古い", "reading": "ふるい", "romaji": "furui"}, "present_negative": {"kanji": "古くない", "reading": "ふるくない", "romaji": "furukunai"}, "past_positive": {"kanji": "古かった", "reading": "ふるかった", "romaji": "furukatta"}, "past_negative": {"kanji": "古くなかった", "reading": "ふるくなかった", "romaji": "furukunakatta"}, "te_form": {"kanji": "古くて", "reading": "ふるくて", "romaji": "furukute"}, "adverb": {"kanji": "古く", "reading": "ふるく", "romaji": "furuku"}}'),

-- Taste
('おいしい', 'おいしい', 'oishii', 'delicious, tasty', 'i_adjective', 'N5', 10, '{"present_positive": {"kanji": "おいしい", "reading": "おいしい", "romaji": "oishii"}, "present_negative": {"kanji": "おいしくない", "reading": "おいしくない", "romaji": "oishikunai"}, "past_positive": {"kanji": "おいしかった", "reading": "おいしかった", "romaji": "oishikatta"}, "past_negative": {"kanji": "おいしくなかった", "reading": "おいしくなかった", "romaji": "oishikunakatta"}, "te_form": {"kanji": "おいしくて", "reading": "おいしくて", "romaji": "oishikute"}, "adverb": {"kanji": "おいしく", "reading": "おいしく", "romaji": "oishiku"}}'),

('まずい', 'まずい', 'mazui', 'unappetizing, bad-tasting', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "まずい", "reading": "まずい", "romaji": "mazui"}, "present_negative": {"kanji": "まずくない", "reading": "まずくない", "romaji": "mazukunai"}, "past_positive": {"kanji": "まずかった", "reading": "まずかった", "romaji": "mazukatta"}, "past_negative": {"kanji": "まずくなかった", "reading": "まずくなかった", "romaji": "mazukunakatta"}, "te_form": {"kanji": "まずくて", "reading": "まずくて", "romaji": "mazukute"}, "adverb": {"kanji": "まずく", "reading": "まずく", "romaji": "mazuku"}}'),

('甘い', 'あまい', 'amai', 'sweet', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "甘い", "reading": "あまい", "romaji": "amai"}, "present_negative": {"kanji": "甘くない", "reading": "あまくない", "romaji": "amakunai"}, "past_positive": {"kanji": "甘かった", "reading": "あまかった", "romaji": "amakatta"}, "past_negative": {"kanji": "甘くなかった", "reading": "あまくなかった", "romaji": "amakunakatta"}, "te_form": {"kanji": "甘くて", "reading": "あまくて", "romaji": "amakute"}, "adverb": {"kanji": "甘く", "reading": "あまく", "romaji": "amaku"}}'),

-- Emotions
('嬉しい', 'うれしい', 'ureshii', 'happy, glad', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "嬉しい", "reading": "うれしい", "romaji": "ureshii"}, "present_negative": {"kanji": "嬉しくない", "reading": "うれしくない", "romaji": "ureshikunai"}, "past_positive": {"kanji": "嬉しかった", "reading": "うれしかった", "romaji": "ureshikatta"}, "past_negative": {"kanji": "嬉しくなかった", "reading": "うれしくなかった", "romaji": "ureshikunakatta"}, "te_form": {"kanji": "嬉しくて", "reading": "うれしくて", "romaji": "ureshikute"}, "adverb": {"kanji": "嬉しく", "reading": "うれしく", "romaji": "ureshiku"}}'),

('悲しい', 'かなしい', 'kanashii', 'sad', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "悲しい", "reading": "かなしい", "romaji": "kanashii"}, "present_negative": {"kanji": "悲しくない", "reading": "かなしくない", "romaji": "kanashikunai"}, "past_positive": {"kanji": "悲しかった", "reading": "かなしかった", "romaji": "kanashikatta"}, "past_negative": {"kanji": "悲しくなかった", "reading": "かなしくなかった", "romaji": "kanashikunakatta"}, "te_form": {"kanji": "悲しくて", "reading": "かなしくて", "romaji": "kanashikute"}, "adverb": {"kanji": "悲しく", "reading": "かなしく", "romaji": "kanashiku"}}'),

('楽しい', 'たのしい', 'tanoshii', 'fun, enjoyable', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "楽しい", "reading": "たのしい", "romaji": "tanoshii"}, "present_negative": {"kanji": "楽しくない", "reading": "たのしくない", "romaji": "tanoshikunai"}, "past_positive": {"kanji": "楽しかった", "reading": "たのしかった", "romaji": "tanoshikatta"}, "past_negative": {"kanji": "楽しくなかった", "reading": "たのしくなかった", "romaji": "tanoshikunakatta"}, "te_form": {"kanji": "楽しくて", "reading": "たのしくて", "romaji": "tanoshikute"}, "adverb": {"kanji": "楽しく", "reading": "たのしく", "romaji": "tanoshiku"}}'),

('つまらない', 'つまらない', 'tsumaranai', 'boring, dull', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "つまらない", "reading": "つまらない", "romaji": "tsumaranai"}, "present_negative": {"kanji": "つまらなくない", "reading": "つまらなくない", "romaji": "tsumaranakunai"}, "past_positive": {"kanji": "つまらなかった", "reading": "つまらなかった", "romaji": "tsumaranakatta"}, "past_negative": {"kanji": "つまらなくなかった", "reading": "つまらなくなかった", "romaji": "tsumaranakunakatta"}, "te_form": {"kanji": "つまらなくて", "reading": "つまらなくて", "romaji": "tsumaranakute"}, "adverb": {"kanji": "つまらなく", "reading": "つまらなく", "romaji": "tsumaranaku"}}'),

('面白い', 'おもしろい', 'omoshiroi', 'interesting, funny', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "面白い", "reading": "おもしろい", "romaji": "omoshiroi"}, "present_negative": {"kanji": "面白くない", "reading": "おもしろくない", "romaji": "omoshirokunai"}, "past_positive": {"kanji": "面白かった", "reading": "おもしろかった", "romaji": "omoshirokatta"}, "past_negative": {"kanji": "面白くなかった", "reading": "おもしろくなかった", "romaji": "omoshirokunakatta"}, "te_form": {"kanji": "面白くて", "reading": "おもしろくて", "romaji": "omoshirokute"}, "adverb": {"kanji": "面白く", "reading": "おもしろく", "romaji": "omoshiroku"}}'),

('怖い', 'こわい', 'kowai', 'scary, frightening', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "怖い", "reading": "こわい", "romaji": "kowai"}, "present_negative": {"kanji": "怖くない", "reading": "こわくない", "romaji": "kowakunai"}, "past_positive": {"kanji": "怖かった", "reading": "こわかった", "romaji": "kowakatta"}, "past_negative": {"kanji": "怖くなかった", "reading": "こわくなかった", "romaji": "kowakunakatta"}, "te_form": {"kanji": "怖くて", "reading": "こわくて", "romaji": "kowakute"}, "adverb": {"kanji": "怖く", "reading": "こわく", "romaji": "kowaku"}}'),

('恥ずかしい', 'はずかしい', 'hazukashii', 'embarrassing, shy', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "恥ずかしい", "reading": "はずかしい", "romaji": "hazukashii"}, "present_negative": {"kanji": "恥ずかしくない", "reading": "はずかしくない", "romaji": "hazukashikunai"}, "past_positive": {"kanji": "恥ずかしかった", "reading": "はずかしかった", "romaji": "hazukashikatta"}, "past_negative": {"kanji": "恥ずかしくなかった", "reading": "はずかしくなかった", "romaji": "hazukashikunakatta"}, "te_form": {"kanji": "恥ずかしくて", "reading": "はずかしくて", "romaji": "hazukashikute"}, "adverb": {"kanji": "恥ずかしく", "reading": "はずかしく", "romaji": "hazukashiku"}}'),

('眠い', 'ねむい', 'nemui', 'sleepy', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "眠い", "reading": "ねむい", "romaji": "nemui"}, "present_negative": {"kanji": "眠くない", "reading": "ねむくない", "romaji": "nemukunai"}, "past_positive": {"kanji": "眠かった", "reading": "ねむかった", "romaji": "nemukatta"}, "past_negative": {"kanji": "眠くなかった", "reading": "ねむくなかった", "romaji": "nemukunakatta"}, "te_form": {"kanji": "眠くて", "reading": "ねむくて", "romaji": "nemukute"}, "adverb": {"kanji": "眠く", "reading": "ねむく", "romaji": "nemuku"}}'),

-- Physical
('痛い', 'いたい', 'itai', 'painful, sore', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "痛い", "reading": "いたい", "romaji": "itai"}, "present_negative": {"kanji": "痛くない", "reading": "いたくない", "romaji": "itakunai"}, "past_positive": {"kanji": "痛かった", "reading": "いたかった", "romaji": "itakatta"}, "past_negative": {"kanji": "痛くなかった", "reading": "いたくなかった", "romaji": "itakunakatta"}, "te_form": {"kanji": "痛くて", "reading": "いたくて", "romaji": "itakute"}, "adverb": {"kanji": "痛く", "reading": "いたく", "romaji": "itaku"}}'),

-- Appearance
('かわいい', 'かわいい', 'kawaii', 'cute', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "かわいい", "reading": "かわいい", "romaji": "kawaii"}, "present_negative": {"kanji": "かわいくない", "reading": "かわいくない", "romaji": "kawaiikunai"}, "past_positive": {"kanji": "かわいかった", "reading": "かわいかった", "romaji": "kawaikatta"}, "past_negative": {"kanji": "かわいくなかった", "reading": "かわいくなかった", "romaji": "kawaiikunakatta"}, "te_form": {"kanji": "かわいくて", "reading": "かわいくて", "romaji": "kawaikute"}, "adverb": {"kanji": "かわいく", "reading": "かわいく", "romaji": "kawaiku"}}'),

('明るい', 'あかるい', 'akarui', 'bright', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "明るい", "reading": "あかるい", "romaji": "akarui"}, "present_negative": {"kanji": "明るくない", "reading": "あかるくない", "romaji": "akarukunai"}, "past_positive": {"kanji": "明るかった", "reading": "あかるかった", "romaji": "akarukatta"}, "past_negative": {"kanji": "明るくなかった", "reading": "あかるくなかった", "romaji": "akarukunakatta"}, "te_form": {"kanji": "明るくて", "reading": "あかるくて", "romaji": "akarukute"}, "adverb": {"kanji": "明るく", "reading": "あかるく", "romaji": "akaruku"}}'),

('暗い', 'くらい', 'kurai', 'dark', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "暗い", "reading": "くらい", "romaji": "kurai"}, "present_negative": {"kanji": "暗くない", "reading": "くらくない", "romaji": "kurakunai"}, "past_positive": {"kanji": "暗かった", "reading": "くらかった", "romaji": "kurakatta"}, "past_negative": {"kanji": "暗くなかった", "reading": "くらくなかった", "romaji": "kurakunakatta"}, "te_form": {"kanji": "暗くて", "reading": "くらくて", "romaji": "kurakute"}, "adverb": {"kanji": "暗く", "reading": "くらく", "romaji": "kuraku"}}'),

('汚い', 'きたない', 'kitanai', 'dirty', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "汚い", "reading": "きたない", "romaji": "kitanai"}, "present_negative": {"kanji": "汚くない", "reading": "きたなくない", "romaji": "kitanakunai"}, "past_positive": {"kanji": "汚かった", "reading": "きたなかった", "romaji": "kitanakatta"}, "past_negative": {"kanji": "汚くなかった", "reading": "きたなくなかった", "romaji": "kitanakunakatta"}, "te_form": {"kanji": "汚くて", "reading": "きたなくて", "romaji": "kitanakute"}, "adverb": {"kanji": "汚く", "reading": "きたなく", "romaji": "kitanaku"}}'),

-- Size & dimensions
('広い', 'ひろい', 'hiroi', 'spacious, wide', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "広い", "reading": "ひろい", "romaji": "hiroi"}, "present_negative": {"kanji": "広くない", "reading": "ひろくない", "romaji": "hirokunakunai"}, "past_positive": {"kanji": "広かった", "reading": "ひろかった", "romaji": "hirokatta"}, "past_negative": {"kanji": "広くなかった", "reading": "ひろくなかった", "romaji": "hirokunakunakatta"}, "te_form": {"kanji": "広くて", "reading": "ひろくて", "romaji": "hirokute"}, "adverb": {"kanji": "広く", "reading": "ひろく", "romaji": "hiroku"}}'),

('狭い', 'せまい', 'semai', 'narrow, cramped', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "狭い", "reading": "せまい", "romaji": "semai"}, "present_negative": {"kanji": "狭くない", "reading": "せまくない", "romaji": "semakunai"}, "past_positive": {"kanji": "狭かった", "reading": "せまかった", "romaji": "semakatta"}, "past_negative": {"kanji": "狭くなかった", "reading": "せまくなかった", "romaji": "semakunakatta"}, "te_form": {"kanji": "狭くて", "reading": "せまくて", "romaji": "semakute"}, "adverb": {"kanji": "狭く", "reading": "せまく", "romaji": "semaku"}}'),

('長い', 'ながい', 'nagai', 'long', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "長い", "reading": "ながい", "romaji": "nagai"}, "present_negative": {"kanji": "長くない", "reading": "ながくない", "romaji": "nagakunai"}, "past_positive": {"kanji": "長かった", "reading": "ながかった", "romaji": "nagakatta"}, "past_negative": {"kanji": "長くなかった", "reading": "ながくなかった", "romaji": "nagakunakatta"}, "te_form": {"kanji": "長くて", "reading": "ながくて", "romaji": "nagakute"}, "adverb": {"kanji": "長く", "reading": "ながく", "romaji": "nagaku"}}'),

('短い', 'みじかい', 'mijikai', 'short', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "短い", "reading": "みじかい", "romaji": "mijikai"}, "present_negative": {"kanji": "短くない", "reading": "みじかくない", "romaji": "mijikakunai"}, "past_positive": {"kanji": "短かった", "reading": "みじかかった", "romaji": "mijikakatta"}, "past_negative": {"kanji": "短くなかった", "reading": "みじかくなかった", "romaji": "mijikakunakatta"}, "te_form": {"kanji": "短くて", "reading": "みじかくて", "romaji": "mijikakute"}, "adverb": {"kanji": "短く", "reading": "みじかく", "romaji": "mijikaku"}}'),

-- Difficulty
('易しい', 'やさしい', 'yasashii', 'easy, gentle', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "易しい", "reading": "やさしい", "romaji": "yasashii"}, "present_negative": {"kanji": "易しくない", "reading": "やさしくない", "romaji": "yasashikunai"}, "past_positive": {"kanji": "易しかった", "reading": "やさしかった", "romaji": "yasashikatta"}, "past_negative": {"kanji": "易しくなかった", "reading": "やさしくなかった", "romaji": "yasashikunakatta"}, "te_form": {"kanji": "易しくて", "reading": "やさしくて", "romaji": "yasashikute"}, "adverb": {"kanji": "易しく", "reading": "やさしく", "romaji": "yasashiku"}}'),

('難しい', 'むずかしい', 'muzukashii', 'difficult', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "難しい", "reading": "むずかしい", "romaji": "muzukashii"}, "present_negative": {"kanji": "難しくない", "reading": "むずかしくない", "romaji": "muzukashikunai"}, "past_positive": {"kanji": "難しかった", "reading": "むずかしかった", "romaji": "muzukashikatta"}, "past_negative": {"kanji": "難しくなかった", "reading": "むずかしくなかった", "romaji": "muzukashikunakatta"}, "te_form": {"kanji": "難しくて", "reading": "むずかしくて", "romaji": "muzukashikute"}, "adverb": {"kanji": "難しく", "reading": "むずかしく", "romaji": "muzukashiku"}}'),

-- Busy
('忙しい', 'いそがしい', 'isogashii', 'busy', 'i_adjective', 'N5', 8, '{"present_positive": {"kanji": "忙しい", "reading": "いそがしい", "romaji": "isogashii"}, "present_negative": {"kanji": "忙しくない", "reading": "いそがしくない", "romaji": "isogashikunai"}, "past_positive": {"kanji": "忙しかった", "reading": "いそがしかった", "romaji": "isogashikatta"}, "past_negative": {"kanji": "忙しくなかった", "reading": "いそがしくなかった", "romaji": "isogashikunakatta"}, "te_form": {"kanji": "忙しくて", "reading": "いそがしくて", "romaji": "isogashikute"}, "adverb": {"kanji": "忙しく", "reading": "いそがしく", "romaji": "isogashiku"}}'),

-- N4 Adjectives

-- Speed
('速い', 'はやい', 'hayai', 'fast, quick', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "速い", "reading": "はやい", "romaji": "hayai"}, "present_negative": {"kanji": "速くない", "reading": "はやくない", "romaji": "hayakunai"}, "past_positive": {"kanji": "速かった", "reading": "はやかった", "romaji": "hayakatta"}, "past_negative": {"kanji": "速くなかった", "reading": "はやくなかった", "romaji": "hayakunakatta"}, "te_form": {"kanji": "速くて", "reading": "はやくて", "romaji": "hayakute"}, "adverb": {"kanji": "速く", "reading": "はやく", "romaji": "hayaku"}}'),

('早い', 'はやい', 'hayai', 'early', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "早い", "reading": "はやい", "romaji": "hayai"}, "present_negative": {"kanji": "早くない", "reading": "はやくない", "romaji": "hayakunai"}, "past_positive": {"kanji": "早かった", "reading": "はやかった", "romaji": "hayakatta"}, "past_negative": {"kanji": "早くなかった", "reading": "はやくなかった", "romaji": "hayakunakatta"}, "te_form": {"kanji": "早くて", "reading": "はやくて", "romaji": "hayakute"}, "adverb": {"kanji": "早く", "reading": "はやく", "romaji": "hayaku"}}'),

('遅い', 'おそい', 'osoi', 'slow, late', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "遅い", "reading": "おそい", "romaji": "osoi"}, "present_negative": {"kanji": "遅くない", "reading": "おそくない", "romaji": "osokunai"}, "past_positive": {"kanji": "遅かった", "reading": "おそかった", "romaji": "osokatta"}, "past_negative": {"kanji": "遅くなかった", "reading": "おそくなかった", "romaji": "osokunakatta"}, "te_form": {"kanji": "遅くて", "reading": "おそくて", "romaji": "osokute"}, "adverb": {"kanji": "遅く", "reading": "おそく", "romaji": "osoku"}}'),

-- Weight & strength
('重い', 'おもい', 'omoi', 'heavy', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "重い", "reading": "おもい", "romaji": "omoi"}, "present_negative": {"kanji": "重くない", "reading": "おもくない", "romaji": "omokunai"}, "past_positive": {"kanji": "重かった", "reading": "おもかった", "romaji": "omokatta"}, "past_negative": {"kanji": "重くなかった", "reading": "おもくなかった", "romaji": "omokunakatta"}, "te_form": {"kanji": "重くて", "reading": "おもくて", "romaji": "omokute"}, "adverb": {"kanji": "重く", "reading": "おもく", "romaji": "omoku"}}'),

('軽い', 'かるい', 'karui', 'light (weight)', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "軽い", "reading": "かるい", "romaji": "karui"}, "present_negative": {"kanji": "軽くない", "reading": "かるくない", "romaji": "karukunai"}, "past_positive": {"kanji": "軽かった", "reading": "かるかった", "romaji": "karukatta"}, "past_negative": {"kanji": "軽くなかった", "reading": "かるくなかった", "romaji": "karukunakatta"}, "te_form": {"kanji": "軽くて", "reading": "かるくて", "romaji": "karukute"}, "adverb": {"kanji": "軽く", "reading": "かるく", "romaji": "karuku"}}'),

('強い', 'つよい', 'tsuyoi', 'strong', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "強い", "reading": "つよい", "romaji": "tsuyoi"}, "present_negative": {"kanji": "強くない", "reading": "つよくない", "romaji": "tsuyokunai"}, "past_positive": {"kanji": "強かった", "reading": "つよかった", "romaji": "tsuyokatta"}, "past_negative": {"kanji": "強くなかった", "reading": "つよくなかった", "romaji": "tsuyokunakatta"}, "te_form": {"kanji": "強くて", "reading": "つよくて", "romaji": "tsuyokute"}, "adverb": {"kanji": "強く", "reading": "つよく", "romaji": "tsuyoku"}}'),

('弱い', 'よわい', 'yowai', 'weak', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "弱い", "reading": "よわい", "romaji": "yowai"}, "present_negative": {"kanji": "弱くない", "reading": "よわくない", "romaji": "yowakunai"}, "past_positive": {"kanji": "弱かった", "reading": "よわかった", "romaji": "yowakatta"}, "past_negative": {"kanji": "弱くなかった", "reading": "よわくなかった", "romaji": "yowakunakatta"}, "te_form": {"kanji": "弱くて", "reading": "よわくて", "romaji": "yowakute"}, "adverb": {"kanji": "弱く", "reading": "よわく", "romaji": "yowaku"}}'),

-- Noise
('うるさい', 'うるさい', 'urusai', 'noisy, annoying', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "うるさい", "reading": "うるさい", "romaji": "urusai"}, "present_negative": {"kanji": "うるさくない", "reading": "うるさくない", "romaji": "urusaikunai"}, "past_positive": {"kanji": "うるさかった", "reading": "うるさかった", "romaji": "urusaikatta"}, "past_negative": {"kanji": "うるさくなかった", "reading": "うるさくなかった", "romaji": "urusaikunakatta"}, "te_form": {"kanji": "うるさくて", "reading": "うるさくて", "romaji": "urusaikute"}, "adverb": {"kanji": "うるさく", "reading": "うるさく", "romaji": "urusaiku"}}'),

-- Taste & smell
('苦い', 'にがい', 'nigai', 'bitter', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "苦い", "reading": "にがい", "romaji": "nigai"}, "present_negative": {"kanji": "苦くない", "reading": "にがくない", "romaji": "nigakunai"}, "past_positive": {"kanji": "苦かった", "reading": "にがかった", "romaji": "nigakatta"}, "past_negative": {"kanji": "苦くなかった", "reading": "にがくなかった", "romaji": "nigakunakatta"}, "te_form": {"kanji": "苦くて", "reading": "にがくて", "romaji": "nigakute"}, "adverb": {"kanji": "苦く", "reading": "にがく", "romaji": "nigaku"}}'),

('酸っぱい', 'すっぱい', 'suppai', 'sour', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "酸っぱい", "reading": "すっぱい", "romaji": "suppai"}, "present_negative": {"kanji": "酸っぱくない", "reading": "すっぱくない", "romaji": "suppaikunai"}, "past_positive": {"kanji": "酸っぱかった", "reading": "すっぱかった", "romaji": "suppaikatta"}, "past_negative": {"kanji": "酸っぱくなかった", "reading": "すっぱくなかった", "romaji": "suppaikunakatta"}, "te_form": {"kanji": "酸っぱくて", "reading": "すっぱくて", "romaji": "suppaikute"}, "adverb": {"kanji": "酸っぱく", "reading": "すっぱく", "romaji": "suppaiku"}}'),

('臭い', 'くさい', 'kusai', 'smelly, stinky', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "臭い", "reading": "くさい", "romaji": "kusai"}, "present_negative": {"kanji": "臭くない", "reading": "くさくない", "romaji": "kusakunai"}, "past_positive": {"kanji": "臭かった", "reading": "くさかった", "romaji": "kusakatta"}, "past_negative": {"kanji": "臭くなかった", "reading": "くさくなかった", "romaji": "kusakunakatta"}, "te_form": {"kanji": "臭くて", "reading": "くさくて", "romaji": "kusakute"}, "adverb": {"kanji": "臭く", "reading": "くさく", "romaji": "kusaku"}}'),

-- Strictness & correctness
('厳しい', 'きびしい', 'kibishii', 'strict, severe', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "厳しい", "reading": "きびしい", "romaji": "kibishii"}, "present_negative": {"kanji": "厳しくない", "reading": "きびしくない", "romaji": "kibishikunai"}, "past_positive": {"kanji": "厳しかった", "reading": "きびしかった", "romaji": "kibishikatta"}, "past_negative": {"kanji": "厳しくなかった", "reading": "きびしくなかった", "romaji": "kibishikunakatta"}, "te_form": {"kanji": "厳しくて", "reading": "きびしくて", "romaji": "kibishikute"}, "adverb": {"kanji": "厳しく", "reading": "きびしく", "romaji": "kibishiku"}}'),

('正しい', 'ただしい', 'tadashii', 'correct, right', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "正しい", "reading": "ただしい", "romaji": "tadashii"}, "present_negative": {"kanji": "正しくない", "reading": "ただしくない", "romaji": "tadashikunai"}, "past_positive": {"kanji": "正しかった", "reading": "ただしかった", "romaji": "tadashikatta"}, "past_negative": {"kanji": "正しくなかった", "reading": "ただしくなかった", "romaji": "tadashikunakatta"}, "te_form": {"kanji": "正しくて", "reading": "ただしくて", "romaji": "tadashikute"}, "adverb": {"kanji": "正しく", "reading": "ただしく", "romaji": "tadashiku"}}'),

-- Desire & quantity
('欲しい', 'ほしい', 'hoshii', 'want, desire', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "欲しい", "reading": "ほしい", "romaji": "hoshii"}, "present_negative": {"kanji": "欲しくない", "reading": "ほしくない", "romaji": "hoshikunai"}, "past_positive": {"kanji": "欲しかった", "reading": "ほしかった", "romaji": "hoshikatta"}, "past_negative": {"kanji": "欲しくなかった", "reading": "ほしくなかった", "romaji": "hoshikunakatta"}, "te_form": {"kanji": "欲しくて", "reading": "ほしくて", "romaji": "hoshikute"}, "adverb": {"kanji": "欲しく", "reading": "ほしく", "romaji": "hoshiku"}}'),

('多い', 'おおい', 'ooi', 'many, much', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "多い", "reading": "おおい", "romaji": "ooi"}, "present_negative": {"kanji": "多くない", "reading": "おおくない", "romaji": "ookukunai"}, "past_positive": {"kanji": "多かった", "reading": "おおかった", "romaji": "ookatta"}, "past_negative": {"kanji": "多くなかった", "reading": "おおくなかった", "romaji": "ookukunakatta"}, "te_form": {"kanji": "多くて", "reading": "おおくて", "romaji": "ookute"}, "adverb": {"kanji": "多く", "reading": "おおく", "romaji": "ooku"}}'),

('少ない', 'すくない', 'sukunai', 'few, little', 'i_adjective', 'N4', 6, '{"present_positive": {"kanji": "少ない", "reading": "すくない", "romaji": "sukunai"}, "present_negative": {"kanji": "少なくない", "reading": "すくなくない", "romaji": "sukunakunai"}, "past_positive": {"kanji": "少なかった", "reading": "すくなかった", "romaji": "sukunakatta"}, "past_negative": {"kanji": "少なくなかった", "reading": "すくなくなかった", "romaji": "sukunakunakatta"}, "te_form": {"kanji": "少なくて", "reading": "すくなくて", "romaji": "sukunakute"}, "adverb": {"kanji": "少なく", "reading": "すくなく", "romaji": "sukunaku"}}')

ON CONFLICT (dictionary_form, reading) DO NOTHING;
