-- Verbs Table with Pre-computed Conjugations
-- This is the core verb database for the grammar engine

-- Create verbs table
CREATE TABLE IF NOT EXISTS verbs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dictionary_form TEXT UNIQUE NOT NULL,
  reading TEXT NOT NULL,
  romaji TEXT NOT NULL,
  meaning TEXT NOT NULL,
  verb_group TEXT NOT NULL CHECK (verb_group IN ('godan', 'ichidan', 'irregular-suru', 'irregular-kuru')),
  jlpt_level TEXT CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
  is_transitive BOOLEAN DEFAULT NULL,
  transitive_pair_id UUID REFERENCES verbs(id),
  intransitive_pair_id UUID REFERENCES verbs(id),
  tags TEXT[] DEFAULT '{}',
  -- Pre-computed conjugations (generated by our algorithm)
  conjugations JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_verbs_reading ON verbs(reading);
CREATE INDEX IF NOT EXISTS idx_verbs_group ON verbs(verb_group);
CREATE INDEX IF NOT EXISTS idx_verbs_jlpt ON verbs(jlpt_level);

-- Insert N5 Verbs (Ichidan)
INSERT INTO verbs (dictionary_form, reading, romaji, meaning, verb_group, jlpt_level, is_transitive, conjugations) VALUES
('食べる', 'たべる', 'taberu', 'to eat', 'ichidan', 'N5', true, '{
  "dictionary": {"kanji": "食べる", "reading": "たべる", "romaji": "taberu"},
  "negative": {"kanji": "食べない", "reading": "たべない", "romaji": "tabenai"},
  "past": {"kanji": "食べた", "reading": "たべた", "romaji": "tabeta"},
  "past_negative": {"kanji": "食べなかった", "reading": "たべなかった", "romaji": "tabenakatta"},
  "masu": {"kanji": "食べます", "reading": "たべます", "romaji": "tabemasu"},
  "masen": {"kanji": "食べません", "reading": "たべません", "romaji": "tabemasen"},
  "mashita": {"kanji": "食べました", "reading": "たべました", "romaji": "tabemashita"},
  "masen_deshita": {"kanji": "食べませんでした", "reading": "たべませんでした", "romaji": "tabemasendeshita"},
  "te": {"kanji": "食べて", "reading": "たべて", "romaji": "tabete"},
  "potential": {"kanji": "食べられる", "reading": "たべられる", "romaji": "taberareru"},
  "volitional": {"kanji": "食べよう", "reading": "たべよう", "romaji": "tabeyou"},
  "imperative": {"kanji": "食べろ", "reading": "たべろ", "romaji": "tabero"},
  "passive": {"kanji": "食べられる", "reading": "たべられる", "romaji": "taberareru"},
  "causative": {"kanji": "食べさせる", "reading": "たべさせる", "romaji": "tabesaseru"},
  "conditional_ba": {"kanji": "食べれば", "reading": "たべれば", "romaji": "tabereba"},
  "conditional_tara": {"kanji": "食べたら", "reading": "たべたら", "romaji": "tabetara"},
  "tai": {"kanji": "食べたい", "reading": "たべたい", "romaji": "tabetai"}
}'::jsonb),

('見る', 'みる', 'miru', 'to see, to watch', 'ichidan', 'N5', true, '{
  "dictionary": {"kanji": "見る", "reading": "みる", "romaji": "miru"},
  "negative": {"kanji": "見ない", "reading": "みない", "romaji": "minai"},
  "past": {"kanji": "見た", "reading": "みた", "romaji": "mita"},
  "masu": {"kanji": "見ます", "reading": "みます", "romaji": "mimasu"},
  "te": {"kanji": "見て", "reading": "みて", "romaji": "mite"},
  "potential": {"kanji": "見られる", "reading": "みられる", "romaji": "mirareru"},
  "volitional": {"kanji": "見よう", "reading": "みよう", "romaji": "miyou"},
  "tai": {"kanji": "見たい", "reading": "みたい", "romaji": "mitai"}
}'::jsonb),

('寝る', 'ねる', 'neru', 'to sleep', 'ichidan', 'N5', false, '{
  "dictionary": {"kanji": "寝る", "reading": "ねる", "romaji": "neru"},
  "negative": {"kanji": "寝ない", "reading": "ねない", "romaji": "nenai"},
  "past": {"kanji": "寝た", "reading": "ねた", "romaji": "neta"},
  "masu": {"kanji": "寝ます", "reading": "ねます", "romaji": "nemasu"},
  "te": {"kanji": "寝て", "reading": "ねて", "romaji": "nete"},
  "tai": {"kanji": "寝たい", "reading": "ねたい", "romaji": "netai"}
}'::jsonb),

('起きる', 'おきる', 'okiru', 'to wake up', 'ichidan', 'N5', false, '{
  "dictionary": {"kanji": "起きる", "reading": "おきる", "romaji": "okiru"},
  "negative": {"kanji": "起きない", "reading": "おきない", "romaji": "okinai"},
  "past": {"kanji": "起きた", "reading": "おきた", "romaji": "okita"},
  "masu": {"kanji": "起きます", "reading": "おきます", "romaji": "okimasu"},
  "te": {"kanji": "起きて", "reading": "おきて", "romaji": "okite"},
  "tai": {"kanji": "起きたい", "reading": "おきたい", "romaji": "okitai"}
}'::jsonb),

('開ける', 'あける', 'akeru', 'to open', 'ichidan', 'N5', true, '{
  "dictionary": {"kanji": "開ける", "reading": "あける", "romaji": "akeru"},
  "negative": {"kanji": "開けない", "reading": "あけない", "romaji": "akenai"},
  "past": {"kanji": "開けた", "reading": "あけた", "romaji": "aketa"},
  "masu": {"kanji": "開けます", "reading": "あけます", "romaji": "akemasu"},
  "te": {"kanji": "開けて", "reading": "あけて", "romaji": "akete"},
  "tai": {"kanji": "開けたい", "reading": "あけたい", "romaji": "aketai"}
}'::jsonb)

ON CONFLICT (dictionary_form) DO UPDATE SET
  reading = EXCLUDED.reading,
  conjugations = EXCLUDED.conjugations,
  updated_at = NOW();

-- Insert N5 Verbs (Godan)
INSERT INTO verbs (dictionary_form, reading, romaji, meaning, verb_group, jlpt_level, is_transitive, conjugations) VALUES
('買う', 'かう', 'kau', 'to buy', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "買う", "reading": "かう", "romaji": "kau"},
  "negative": {"kanji": "買わない", "reading": "かわない", "romaji": "kawanai"},
  "past": {"kanji": "買った", "reading": "かった", "romaji": "katta"},
  "past_negative": {"kanji": "買わなかった", "reading": "かわなかった", "romaji": "kawanakatta"},
  "masu": {"kanji": "買います", "reading": "かいます", "romaji": "kaimasu"},
  "masen": {"kanji": "買いません", "reading": "かいません", "romaji": "kaimasen"},
  "mashita": {"kanji": "買いました", "reading": "かいました", "romaji": "kaimashita"},
  "te": {"kanji": "買って", "reading": "かって", "romaji": "katte"},
  "potential": {"kanji": "買える", "reading": "かえる", "romaji": "kaeru"},
  "volitional": {"kanji": "買おう", "reading": "かおう", "romaji": "kaou"},
  "imperative": {"kanji": "買え", "reading": "かえ", "romaji": "kae"},
  "passive": {"kanji": "買われる", "reading": "かわれる", "romaji": "kawareru"},
  "causative": {"kanji": "買わせる", "reading": "かわせる", "romaji": "kawaseru"},
  "conditional_ba": {"kanji": "買えば", "reading": "かえば", "romaji": "kaeba"},
  "conditional_tara": {"kanji": "買ったら", "reading": "かったら", "romaji": "kattara"},
  "tai": {"kanji": "買いたい", "reading": "かいたい", "romaji": "kaitai"}
}'::jsonb),

('書く', 'かく', 'kaku', 'to write', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "書く", "reading": "かく", "romaji": "kaku"},
  "negative": {"kanji": "書かない", "reading": "かかない", "romaji": "kakanai"},
  "past": {"kanji": "書いた", "reading": "かいた", "romaji": "kaita"},
  "masu": {"kanji": "書きます", "reading": "かきます", "romaji": "kakimasu"},
  "te": {"kanji": "書いて", "reading": "かいて", "romaji": "kaite"},
  "potential": {"kanji": "書ける", "reading": "かける", "romaji": "kakeru"},
  "volitional": {"kanji": "書こう", "reading": "かこう", "romaji": "kakou"},
  "tai": {"kanji": "書きたい", "reading": "かきたい", "romaji": "kakitai"}
}'::jsonb),

('聞く', 'きく', 'kiku', 'to listen, to ask', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "聞く", "reading": "きく", "romaji": "kiku"},
  "negative": {"kanji": "聞かない", "reading": "きかない", "romaji": "kikanai"},
  "past": {"kanji": "聞いた", "reading": "きいた", "romaji": "kiita"},
  "masu": {"kanji": "聞きます", "reading": "ききます", "romaji": "kikimasu"},
  "te": {"kanji": "聞いて", "reading": "きいて", "romaji": "kiite"},
  "tai": {"kanji": "聞きたい", "reading": "ききたい", "romaji": "kikitai"}
}'::jsonb),

('行く', 'いく', 'iku', 'to go', 'godan', 'N5', false, '{
  "dictionary": {"kanji": "行く", "reading": "いく", "romaji": "iku"},
  "negative": {"kanji": "行かない", "reading": "いかない", "romaji": "ikanai"},
  "past": {"kanji": "行った", "reading": "いった", "romaji": "itta"},
  "masu": {"kanji": "行きます", "reading": "いきます", "romaji": "ikimasu"},
  "te": {"kanji": "行って", "reading": "いって", "romaji": "itte"},
  "potential": {"kanji": "行ける", "reading": "いける", "romaji": "ikeru"},
  "volitional": {"kanji": "行こう", "reading": "いこう", "romaji": "ikou"},
  "tai": {"kanji": "行きたい", "reading": "いきたい", "romaji": "ikitai"}
}'::jsonb),

('話す', 'はなす', 'hanasu', 'to speak', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "話す", "reading": "はなす", "romaji": "hanasu"},
  "negative": {"kanji": "話さない", "reading": "はなさない", "romaji": "hanasanai"},
  "past": {"kanji": "話した", "reading": "はなした", "romaji": "hanashita"},
  "masu": {"kanji": "話します", "reading": "はなします", "romaji": "hanashimasu"},
  "te": {"kanji": "話して", "reading": "はなして", "romaji": "hanashite"},
  "tai": {"kanji": "話したい", "reading": "はなしたい", "romaji": "hanashitai"}
}'::jsonb),

('待つ', 'まつ', 'matsu', 'to wait', 'godan', 'N5', false, '{
  "dictionary": {"kanji": "待つ", "reading": "まつ", "romaji": "matsu"},
  "negative": {"kanji": "待たない", "reading": "またない", "romaji": "matanai"},
  "past": {"kanji": "待った", "reading": "まった", "romaji": "matta"},
  "masu": {"kanji": "待ちます", "reading": "まちます", "romaji": "machimasu"},
  "te": {"kanji": "待って", "reading": "まって", "romaji": "matte"},
  "tai": {"kanji": "待ちたい", "reading": "まちたい", "romaji": "machitai"}
}'::jsonb),

('読む', 'よむ', 'yomu', 'to read', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "読む", "reading": "よむ", "romaji": "yomu"},
  "negative": {"kanji": "読まない", "reading": "よまない", "romaji": "yomanai"},
  "past": {"kanji": "読んだ", "reading": "よんだ", "romaji": "yonda"},
  "masu": {"kanji": "読みます", "reading": "よみます", "romaji": "yomimasu"},
  "te": {"kanji": "読んで", "reading": "よんで", "romaji": "yonde"},
  "tai": {"kanji": "読みたい", "reading": "よみたい", "romaji": "yomitai"}
}'::jsonb),

('飲む', 'のむ', 'nomu', 'to drink', 'godan', 'N5', true, '{
  "dictionary": {"kanji": "飲む", "reading": "のむ", "romaji": "nomu"},
  "negative": {"kanji": "飲まない", "reading": "のまない", "romaji": "nomanai"},
  "past": {"kanji": "飲んだ", "reading": "のんだ", "romaji": "nonda"},
  "masu": {"kanji": "飲みます", "reading": "のみます", "romaji": "nomimasu"},
  "te": {"kanji": "飲んで", "reading": "のんで", "romaji": "nonde"},
  "tai": {"kanji": "飲みたい", "reading": "のみたい", "romaji": "nomitai"}
}'::jsonb),

('遊ぶ', 'あそぶ', 'asobu', 'to play', 'godan', 'N5', false, '{
  "dictionary": {"kanji": "遊ぶ", "reading": "あそぶ", "romaji": "asobu"},
  "negative": {"kanji": "遊ばない", "reading": "あそばない", "romaji": "asobanai"},
  "past": {"kanji": "遊んだ", "reading": "あそんだ", "romaji": "asonda"},
  "masu": {"kanji": "遊びます", "reading": "あそびます", "romaji": "asobimasu"},
  "te": {"kanji": "遊んで", "reading": "あそんで", "romaji": "asonde"},
  "tai": {"kanji": "遊びたい", "reading": "あそびたい", "romaji": "asobitai"}
}'::jsonb),

('帰る', 'かえる', 'kaeru', 'to return, to go home', 'godan', 'N5', false, '{
  "dictionary": {"kanji": "帰る", "reading": "かえる", "romaji": "kaeru"},
  "negative": {"kanji": "帰らない", "reading": "かえらない", "romaji": "kaeranai"},
  "past": {"kanji": "帰った", "reading": "かえった", "romaji": "kaetta"},
  "masu": {"kanji": "帰ります", "reading": "かえります", "romaji": "kaerimasu"},
  "te": {"kanji": "帰って", "reading": "かえって", "romaji": "kaette"},
  "tai": {"kanji": "帰りたい", "reading": "かえりたい", "romaji": "kaeritai"}
}'::jsonb),

('泳ぐ', 'およぐ', 'oyogu', 'to swim', 'godan', 'N5', false, '{
  "dictionary": {"kanji": "泳ぐ", "reading": "およぐ", "romaji": "oyogu"},
  "negative": {"kanji": "泳がない", "reading": "およがない", "romaji": "oyoganai"},
  "past": {"kanji": "泳いだ", "reading": "およいだ", "romaji": "oyoida"},
  "masu": {"kanji": "泳ぎます", "reading": "およぎます", "romaji": "oyogimasu"},
  "te": {"kanji": "泳いで", "reading": "およいで", "romaji": "oyoide"},
  "tai": {"kanji": "泳ぎたい", "reading": "およぎたい", "romaji": "oyogitai"}
}'::jsonb)

ON CONFLICT (dictionary_form) DO UPDATE SET
  reading = EXCLUDED.reading,
  conjugations = EXCLUDED.conjugations,
  updated_at = NOW();

-- Insert Irregular Verbs
INSERT INTO verbs (dictionary_form, reading, romaji, meaning, verb_group, jlpt_level, is_transitive, conjugations) VALUES
('する', 'する', 'suru', 'to do', 'irregular-suru', 'N5', false, '{
  "dictionary": {"kanji": "する", "reading": "する", "romaji": "suru"},
  "negative": {"kanji": "しない", "reading": "しない", "romaji": "shinai"},
  "past": {"kanji": "した", "reading": "した", "romaji": "shita"},
  "past_negative": {"kanji": "しなかった", "reading": "しなかった", "romaji": "shinakatta"},
  "masu": {"kanji": "します", "reading": "します", "romaji": "shimasu"},
  "masen": {"kanji": "しません", "reading": "しません", "romaji": "shimasen"},
  "mashita": {"kanji": "しました", "reading": "しました", "romaji": "shimashita"},
  "te": {"kanji": "して", "reading": "して", "romaji": "shite"},
  "potential": {"kanji": "できる", "reading": "できる", "romaji": "dekiru"},
  "volitional": {"kanji": "しよう", "reading": "しよう", "romaji": "shiyou"},
  "imperative": {"kanji": "しろ", "reading": "しろ", "romaji": "shiro"},
  "passive": {"kanji": "される", "reading": "される", "romaji": "sareru"},
  "causative": {"kanji": "させる", "reading": "させる", "romaji": "saseru"},
  "conditional_ba": {"kanji": "すれば", "reading": "すれば", "romaji": "sureba"},
  "conditional_tara": {"kanji": "したら", "reading": "したら", "romaji": "shitara"},
  "tai": {"kanji": "したい", "reading": "したい", "romaji": "shitai"}
}'::jsonb),

('来る', 'くる', 'kuru', 'to come', 'irregular-kuru', 'N5', false, '{
  "dictionary": {"kanji": "来る", "reading": "くる", "romaji": "kuru"},
  "negative": {"kanji": "来ない", "reading": "こない", "romaji": "konai"},
  "past": {"kanji": "来た", "reading": "きた", "romaji": "kita"},
  "past_negative": {"kanji": "来なかった", "reading": "こなかった", "romaji": "konakatta"},
  "masu": {"kanji": "来ます", "reading": "きます", "romaji": "kimasu"},
  "masen": {"kanji": "来ません", "reading": "きません", "romaji": "kimasen"},
  "mashita": {"kanji": "来ました", "reading": "きました", "romaji": "kimashita"},
  "te": {"kanji": "来て", "reading": "きて", "romaji": "kite"},
  "potential": {"kanji": "来られる", "reading": "こられる", "romaji": "korareru"},
  "volitional": {"kanji": "来よう", "reading": "こよう", "romaji": "koyou"},
  "imperative": {"kanji": "来い", "reading": "こい", "romaji": "koi"},
  "passive": {"kanji": "来られる", "reading": "こられる", "romaji": "korareru"},
  "causative": {"kanji": "来させる", "reading": "こさせる", "romaji": "kosaseru"},
  "conditional_ba": {"kanji": "来れば", "reading": "くれば", "romaji": "kureba"},
  "conditional_tara": {"kanji": "来たら", "reading": "きたら", "romaji": "kitara"},
  "tai": {"kanji": "来たい", "reading": "きたい", "romaji": "kitai"}
}'::jsonb),

-- する compound verbs
('勉強する', 'べんきょうする', 'benkyou suru', 'to study', 'irregular-suru', 'N5', false, '{
  "dictionary": {"kanji": "勉強する", "reading": "べんきょうする", "romaji": "benkyou suru"},
  "negative": {"kanji": "勉強しない", "reading": "べんきょうしない", "romaji": "benkyou shinai"},
  "past": {"kanji": "勉強した", "reading": "べんきょうした", "romaji": "benkyou shita"},
  "masu": {"kanji": "勉強します", "reading": "べんきょうします", "romaji": "benkyou shimasu"},
  "te": {"kanji": "勉強して", "reading": "べんきょうして", "romaji": "benkyou shite"},
  "tai": {"kanji": "勉強したい", "reading": "べんきょうしたい", "romaji": "benkyou shitai"}
}'::jsonb)

ON CONFLICT (dictionary_form) DO UPDATE SET
  reading = EXCLUDED.reading,
  conjugations = EXCLUDED.conjugations,
  updated_at = NOW();

-- Create function to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger
DROP TRIGGER IF EXISTS update_verbs_updated_at ON verbs;
CREATE TRIGGER update_verbs_updated_at
  BEFORE UPDATE ON verbs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
